/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz;

public class App {
    public static void fizzbuzz() {
        System.out.println("Welcome to Fezz Buzz!"); // Display the string.
        int fizz = 3;
        int buzz = 5;
        for (int counter = 0; counter <= 100; counter++) {
            if (isaDivider(fizz, counter) && isaDivider(buzz, counter)) {
                System.out.println("FizzBuzz");
            } else if (isaDivider(fizz, counter) && !isaDivider(buzz, counter)) {
                System.out.println("Fizz");
            } else if (!isaDivider(fizz, counter) && isaDivider(buzz, counter)) {
                System.out.println("Buzz");
            } else {
                System.out.println(counter);
            }
          }
    }
    public static Boolean isaDivider(int divider, int numberToCheck){
        return numberToCheck % divider == 0;
    }
    public static void main(String[] args) {
        fizzbuzz();
    }
}
