/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package fizzbuzz;

public class App {
    public static void fizzbuzz() {
        System.out.println("Welcome to Fezz Buzz!"); // Display the string.
        int fizz = 3;
        int buzz = 5;
        int bang = 7;
        int bong = 11;
        int fezz = 13;
        int reserve = 17;


        for (int counter = 0; counter <= 1000; counter++) {
            String sentence = "";
            Boolean isFizz = false; // 3
            Boolean isBuzz = false; // 5
            Boolean isBang = false; // 7
            Boolean isBong = false; // 11
            Boolean isFezz = false; // 13
            Boolean isReverse = false; // 17
            isBong = isaDivider(bong, counter); // if true display bong only
            if (isBong){
                System.out.println("Bong");
            } else {
                sentence += addWord(fizz, counter, "Fizz");
                sentence += addWord(fezz, counter, "Fezz");
                sentence += addWord(buzz, counter, "Buzz");
                sentence += addWord(bang, counter, "Bang");
                if (sentence.length() == 0) {
                    System.out.println(counter);
                } else {
                        isReverse = isaDivider(reserve, counter);
                        if (isReverse) {
                            String reversed = reverseSentence(sentence);
                            System.out.println(reversed);
                        } else {
                            System.out.println(sentence);
                        }
                    }
            }
        }
    }

    public static Boolean isaDivider(int divider, int numberToCheck) {
        return numberToCheck % divider == 0;
    }
    public static String addWord(int divider, int numberToCheck, String wordToAdd) {
        if (isaDivider(divider, numberToCheck)) {
            return wordToAdd;
        } else {
            return "";
        }
    }
    public static String reverseSentence(String setenceToReverse) {
        return "reverseSentence";
    }
    public static void main(String[] args) {
        fizzbuzz();
    }
}
